message:
  # ✅
  # 重要信息
  #
  # 与女朋友相识的日子
  start_stamp: 2021-03-26
  # 卡片标题信息（加粗显示）：今天是我们相恋的第 {day} 天，这里的 {day} 为固定替换相恋多久
  start_stamp_message: 今天是我们相恋的第 {day} 天
  # 女朋友所在城市（不要带‘市’），天气接口需要使用
  city_name: 杭州
  # 女朋友的爱称
  girl_name: 臭猪
  # 对自己的称呼
  boy_name: baby
  # 农历信息（默认开启）
  date_lunarInfo: true
  # 黄历信息（默认关闭）
  date_huangli: false
  # 卡片末尾自定义信息（为空则不显示）
  card_end_message: "\n今天也是元气满满的一天~"
  # 点击卡片详情地址
  card_url: https://api.vvhan.com/api/60s
